nome = input('Digite seu nome: ')
idade = input('Digite sua idade: ')
print('Meu nome é', nome, sep=' ', end='')
print(', minha idade é', idade, end='')
print(', e meu cpf é', end=' ')
print('492', '453', '342', sep='.', end='-')
print('34')